script: 'ci/travis.rb'
rvm:
  - 1.8.7
  - 1.9.3
env:
  - "GEM=ar:mysql2"
  - "GEM=ar:postgresql"
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
bundler_args: --path vendor/bundle
